"""End-of-day email digest — portfolio summary + news highlights."""

import argparse
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from db import get_conn, init_db
from config import GMAIL_ADDRESS, GMAIL_APP_PASSWORD, DIGEST_TO, TIMEZONE
from prices import fetch_all_prices
from news import fetch_news_for_holdings


def build_digest():
    """Build the digest email content."""
    init_db()
    conn = get_conn()
    holdings = conn.execute("SELECT * FROM holdings ORDER BY symbol").fetchall()
    conn.close()

    prices = fetch_all_prices()
    news = fetch_news_for_holdings()

    now = datetime.now().strftime("%B %d, %Y %I:%M %p")

    lines = []
    lines.append(f"📊 robnhud Daily Digest — {now}")
    lines.append("=" * 50)
    lines.append("")

    # Portfolio summary
    lines.append("PORTFOLIO SUMMARY")
    lines.append("-" * 50)

    total_value = 0
    total_cost = 0

    for h in holdings:
        sym = h["symbol"]
        qty = h["qty"]
        avg_cost = h["avg_cost"]
        p = prices.get(sym)

        if p:
            price = p["price"]
            change = p["change_pct"]
            value = price * qty
            total_value += value

            if avg_cost:
                cost_basis = avg_cost * qty
                total_cost += cost_basis
                pl = value - cost_basis
                pl_pct = (pl / cost_basis) * 100
                pl_str = f"{'+'if pl>=0 else ''}{pl:.2f} ({pl_pct:+.1f}%)"
            else:
                pl_str = "—"

            change_str = f"{'+'if change>=0 else ''}{change:.1f}%"
            lines.append(f"  {sym:<8} {qty:>10.4f} @ ${price:.4f}  = ${value:.2f}  24h: {change_str}  P/L: {pl_str}")

    lines.append("")
    if total_cost > 0:
        total_pl = total_value - total_cost
        total_pct = (total_pl / total_cost) * 100
        lines.append(f"  TOTAL VALUE: ${total_value:.2f}  |  P/L: {'+'if total_pl>=0 else ''}{total_pl:.2f} ({total_pct:+.1f}%)")
    else:
        lines.append(f"  TOTAL VALUE: ${total_value:.2f}")

    # Alert activity
    lines.append("")
    lines.append("ALERTS FIRED TODAY")
    lines.append("-" * 50)

    conn = get_conn()
    today = datetime.now().strftime("%Y-%m-%d")
    events = conn.execute(
        "SELECT * FROM alert_events WHERE fired_at LIKE ? ORDER BY fired_at DESC",
        (f"{today}%",)
    ).fetchall()
    conn.close()

    if events:
        for e in events:
            lines.append(f"  {e['fired_at']} — {e['symbol']} hit ${e['price']:.4f}")
    else:
        lines.append("  No alerts fired today.")

    # News highlights
    lines.append("")
    lines.append("NEWS HIGHLIGHTS")
    lines.append("-" * 50)

    if news:
        for article in news[:10]:
            ts = article.get("datetime", 0)
            if ts:
                dt = datetime.fromtimestamp(ts).strftime("%I:%M%p")
            else:
                dt = ""
            lines.append(f"  [{dt}] {article['headline'][:80]}")
            lines.append(f"         {article['source']} — {article['url']}")
            lines.append("")
    else:
        lines.append("  No relevant news today.")

    lines.append("")
    lines.append("—")
    lines.append("Generated by robnhud • github.com/your-repo")

    return "\n".join(lines)


def send_digest():
    """Send the digest email via Gmail SMTP."""
    if not GMAIL_ADDRESS or not GMAIL_APP_PASSWORD:
        print("Gmail credentials not configured in .env")
        print("Set GMAIL_ADDRESS and GMAIL_APP_PASSWORD")
        return

    body = build_digest()

    msg = MIMEMultipart()
    msg["From"] = GMAIL_ADDRESS
    msg["To"] = DIGEST_TO
    msg["Subject"] = f"📊 robnhud Digest — {datetime.now().strftime('%b %d, %Y')}"
    msg.attach(MIMEText(body, "plain"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
            server.sendmail(GMAIL_ADDRESS, DIGEST_TO, msg.as_string())
        print("Digest email sent!")
    except Exception as e:
        print(f"Email error: {e}")


def preview():
    """Print the digest to screen without sending."""
    import sys, io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    print(build_digest())


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="End-of-day email digest")
    parser.add_argument("--send", action="store_true", help="Send the digest email")
    parser.add_argument("--preview", action="store_true", help="Preview without sending")
    args = parser.parse_args()

    if args.send:
        send_digest()
    elif args.preview:
        preview()
    else:
        parser.print_help()
